import type { MarkdownPostProcessorContext } from "obsidian";
import type { EditorView } from "@codemirror/view";
import { DEFAULT_SVG_PARTIAL, DEFAULT_SVG_CHECK, DEFAULT_SVG_BANG, DEFAULT_SVG_QUESTION, DEFAULT_SVG_SLASH } from "./icons";

/**
 * A checkbox variant to be stored in the settings.
 */
export interface CheckboxVariant {
	/** Stable id. Generated by the plugin. */
	id: string;
	/** The character that appears between the brackets. */
	character: string;
	/** Human-friendly label shown in the variant menu. */
	name: string;
	/** Raw SVG source rendered as the icon. */
	svgSource: string;
	/** When true, the whole task line gets strikethrough styling. */
	completed: boolean;
	/** Optional color override applied to SVG. */
	color: string;
}

/**
 * The settings for the plugin.
 */
export interface CustomCheckboxesSettings {
	/** All configured checkbox variants. */
	variants: CheckboxVariant[];
	/** The character of the variant that is considered checked when the user clicks on an empty checkbox. */
	defaultCheckedCharacter: string;
	/** Whether to enable the reading view integration. */
	enableReadingView: boolean;
	/** Whether to enable the live preview integration. */
	enableLivePreview: boolean;
}

/** The duration of a long press to open the menu. */
export const LONG_PRESS_MS = 250;

export const DEFAULT_SETTINGS: CustomCheckboxesSettings = {
	variants: [
		{ id: "v-inprogress", character: "/", name: "In Progress", svgSource: DEFAULT_SVG_PARTIAL, completed: false, color: "" },
		{ id: "v-checked", character: "x", name: "Done", svgSource: DEFAULT_SVG_CHECK, completed: true, color: "" },
		{ id: "v-important", character: "!", name: "Important", svgSource: DEFAULT_SVG_BANG, completed: false, color: "" },
		{ id: "v-question", character: "?", name: "Unsure", svgSource: DEFAULT_SVG_QUESTION, completed: false, color: "" },
		{ id: "v-cancelled", character: "-", name: "Cancelled", svgSource: DEFAULT_SVG_SLASH, completed: true, color: "" },
	],
	defaultCheckedCharacter: "x",
	enableReadingView: true,
	enableLivePreview: true,
};

/** Matches a task list line:  - [x] something */
export const TASK_LINE_REGEX = /^(\s*[-*+]\s+(?:\[\d+\]\s+)?)\[(.)\]/;


/** A target for a checkbox click in the reading view. */
export type ReadingIconTarget = {
	kind: "reading";
	ctx: MarkdownPostProcessorContext;
	el: HTMLElement;
	targetEl: HTMLElement;
}

/** A target for a checkbox click in the live preview. */
export type LiveIconTarget = {
	kind: "live";
	view: EditorView;
	getLineNumber: () => number | null;
	iconEl?: HTMLElement;
}

/** A target for a checkbox click. */
export type IconTarget = ReadingIconTarget | LiveIconTarget;
